name: TeX to Markdown conversion

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "foo" > input.txt  # create an example file
      - uses: docker://pandoc/latex:3.0
        with:
          args: >- 
            --standalone
            --output=README.md
            main.tex
