name: TeX to PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Pull everything
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          
      - name: Convert to PDF
        uses: closoco/pdflatex-action@v1.0.0
        with:
          texFile: main.tex
          
      - name: Remove auxiliary files
        run: |
          rm *.aux
          rm *.log
          rm *.out
          
      - name: Push changes
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: '.'
          message: 'TeX to PDF conversion'
